In [3]:
import pandas as pd 
import numpy as np

In [4]:
data = np.array([[1,4], [2,5], [3,6]])
data

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
df = pd.DataFrame(data, index=["row1", "row2", "row3"], columns= ["col1", "col2"])
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

In [6]:
sehirler = ["Isparta", "Antalya", "Ankara", "Burdur"]
nufus = ["1", "2", "3", "4"]
dict_states = {"Sehirler":sehirler, "Nufus":nufus}
df_nufus = pd.DataFrame(dict_states)
df_nufus

  Sehirler Nufus
0  Isparta     1
1  Antalya     2
2   Ankara     3
3   Burdur     4

In [7]:
# pd.read_csv()

In [8]:
df_exams = pd.read_csv("StudentsPerformance.csv")
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [9]:
df_exams.shape

(1000, 8)

In [10]:
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [11]:
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [12]:
df_exams.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [13]:
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [14]:
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [15]:
df_exams["gender"]

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [16]:
df_exams.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [17]:
df_exams["math score"]

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

In [18]:
df_exams[["gender", "math score"]]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [19]:
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

# Sütun ekleme

In [20]:
df_exams["language score"] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

In [21]:
language_score = np.arange(0,1000)
len(language_score)

1000

In [22]:
df_exams["language score"] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [23]:
int_language_score = np.random.randint(1,100, size=1000)
print(min(int_language_score))
print(max(int_language_score))

1
99

In [24]:
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,38
1,female,group C,some college,standard,completed,69,90,88,2
2,female,group B,master's degree,standard,none,90,95,93,39
3,male,group A,associate's degree,free/reduced,none,47,57,44,88
4,male,group C,some college,standard,none,76,78,75,21
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,15
996,male,group C,high school,free/reduced,none,62,55,55,90
997,female,group C,high school,free/reduced,completed,59,71,65,73
998,female,group D,some college,standard,completed,68,78,77,13
999,female,group D,some college,free/reduced,none,77,86,86,9

## assign

In [25]:
score1 = np.random.randint(1,100, size=1000)
score2 = np.random.randint(1,100, size=1000)
score2

array([99, 22, 64, 97, 59, 81, 33, 14, 33, 76, 98, 53, 31, 66,  6, 55, 57,
        1, 76, 85, 68, 91, 76, 52, 55, 99, 96, 58, 17, 59, 94, 77,  4, 34,
       54, 83, 47, 77, 65, 79, 23, 99,  4, 10, 85, 39, 29, 81,  4, 56, 77,
       49, 73, 78, 99, 68, 42, 48, 77, 71, 16, 82, 38, 78,  7, 99, 14, 44,
       61, 72, 18, 29, 99, 92, 14, 20, 98,  3, 80, 13, 10, 44, 71, 97, 81,
        5, 73, 54, 22, 31, 60, 67, 34, 81, 58, 98,  4,  8, 15, 85, 10, 47,
       81, 71, 59, 30, 45, 11, 23, 57, 88, 26, 50, 75, 47, 63, 31,  7, 76,
       44, 97, 13, 14, 74, 36, 20, 48, 23, 32, 84, 84, 12, 98, 29,  4, 75,
       11, 34, 18, 51, 44, 84, 54, 93, 50, 93, 83, 27, 39, 83, 81,  4, 21,
       32, 55, 52, 21, 21, 14, 59, 19, 39, 62, 77,  4, 25, 87, 77, 94, 71,
       85, 81, 70, 19, 37, 33, 47, 86, 62, 60, 37, 25, 83, 50, 67, 53, 62,
       91, 19, 32, 98, 73, 31, 26, 35, 90, 11, 82, 43, 15, 64, 25, 90,  3,
        1,  2, 44, 96,  4, 91, 96, 57,  9, 17, 60, 57, 91, 49, 95, 54, 11,
        8, 98, 76, 50, 50, 70, 95, 56, 79, 98, 63, 54, 62, 59,  4, 17, 96,
       90, 64, 66, 96, 95, 41, 74,  8, 10, 53,  9, 39, 98, 95, 37, 80, 40,
       85,  7, 59, 69, 62, 20, 50,  1, 75, 52, 65, 91, 35, 96, 82, 45, 27,
       17, 13, 57, 99, 57, 81,  7, 66, 24, 58, 80, 14, 49, 86, 59, 31, 34,
       88, 40, 60, 13, 12,  2, 42, 37, 37, 63, 27,  6, 55, 88,  4, 95, 69,
       73, 77, 60,  4, 85, 60,  9, 38, 37, 49, 99, 25, 17, 71, 62, 99, 90,
       71, 33, 24, 42, 54, 54, 39, 71, 76, 86, 34,  9, 72, 79, 40, 88, 52,
       59, 75, 38, 80, 79, 56, 37, 77, 34, 92, 49, 17, 13, 71, 99, 34, 11,
       94, 21, 51, 91,  9, 13, 59, 21, 91, 97, 73, 39, 15, 11, 60, 88, 11,
       51, 23, 77, 24, 31, 75, 91, 84, 30, 80, 85, 46, 72, 62, 88, 36, 76,
       16, 64, 10, 11, 24, 24, 52, 56, 92,  1, 50, 53, 58, 32, 82, 37, 51,
       43, 35, 12, 53, 35, 33, 12, 67, 95, 50, 37, 13, 46, 29, 33, 76, 83,
       18, 40, 12, 82,  9, 11, 77, 51, 78, 58,  5, 23, 98, 20,  3,  4, 16,
        8, 29, 70, 58, 67, 27, 54, 71, 53, 72, 17, 36, 55, 18,  1, 44, 88,
        7, 50, 30, 16, 50, 22, 79,  9, 62, 40, 22, 49, 48, 97, 30, 10, 81,
       56,  1, 30, 90, 19, 30,  8, 66, 59, 95, 28, 89, 60, 66,  5, 96, 18,
       99, 67, 62, 40, 82, 90, 31, 30, 77, 86, 66, 96, 52, 30, 44, 93, 21,
       93, 99,  5, 70, 16, 21, 28, 38, 35, 51, 21, 59, 25, 91, 58, 91, 12,
        8, 15, 81, 59, 68, 29,  8, 67, 65, 47, 94, 69, 57, 37, 66,  5, 20,
       76, 41, 71, 91, 65, 91, 43, 99, 53, 78, 33,  1, 57, 42, 22,  4,  1,
       79, 76, 33, 96, 71, 57, 23, 32, 36, 14, 78, 76, 75, 94, 74, 90, 71,
       12, 54, 86,  5, 66, 56, 18, 44, 66, 21, 73, 68, 52, 68,  7, 13, 33,
       44, 93, 75,  7, 93, 17, 17, 24, 45, 21, 39, 92, 10,  9, 57, 49, 70,
       58, 34,  8, 73, 79, 33, 74, 20, 83, 42, 11, 58, 44, 67, 98, 74, 60,
       30, 90, 38, 50, 68, 44, 30, 60, 74, 94, 83, 90, 94, 44, 44, 64,  5,
        9, 37, 26, 12, 83, 17, 83, 57, 56, 18, 80, 86, 46, 48, 12, 67, 29,
       22, 35, 14, 95, 85, 55, 56, 50, 93, 65, 66,  9, 63, 36, 61, 45, 11,
       60, 68,  9, 84, 27, 13, 25, 16, 73, 51, 67, 15, 50, 34, 61, 44, 45,
       19, 29, 65, 45, 99, 10, 62, 54, 17, 20, 26, 94, 51, 43, 34, 21, 16,
       93, 21, 96, 87, 97, 50, 66, 34, 68, 73, 12, 42, 54, 91, 95, 35, 61,
       69, 95, 91,  5,  8, 25, 73, 81, 40, 86, 81, 15, 66, 65, 69, 96, 36,
       21, 55, 63, 79, 62, 20, 62, 77, 44, 58, 84, 46, 25, 72,  7,  5, 27,
        7, 68, 16, 95,  2, 70,  5, 81, 32, 78,  5, 35, 31, 93, 29, 28, 49,
       80, 55, 27, 47, 43, 48, 81, 52, 55, 95, 88, 45, 97, 36, 83, 93,  6,
       41, 58, 88, 28, 68, 63, 24, 35, 80, 36, 29, 53, 24, 89, 62, 71, 84,
        5, 59, 23,  6,  8, 56, 93, 44, 39,  3, 98, 13, 52, 51, 23, 41, 41,
       73, 17, 51, 99, 69, 58, 44, 83, 30,  5, 61, 45, 81, 81, 30, 42, 30,
       35, 66, 19,  8, 98, 41,  9, 47, 37, 17, 17, 95, 48, 87, 68, 50, 12,
       41, 18, 76, 24, 47, 91, 78, 25, 64, 41, 41, 81, 76, 69, 38, 65, 84,
       41, 96, 36,  4, 82, 62,  8, 90, 10, 81, 70,  1, 94, 56, 74, 26, 92,
       41, 85, 60, 28, 54, 48, 55, 24, 97, 22, 47, 50, 26,  7, 52, 28, 89,
       47, 78, 72, 81, 84, 58, 43, 80, 90, 60, 55, 22, 95, 75, 43, 39, 80,
       72, 68,  3, 75, 97, 55, 44, 98, 91, 13, 91, 36, 28, 32, 84, 10, 71,
       11, 68,  7, 52, 55, 39, 99, 65, 60, 57, 71, 86, 65, 16,  1, 66, 35,
       12, 42, 30, 36, 31, 78, 14, 40,  7, 91, 12, 89, 92, 73, 22, 74, 98,
       93, 36, 37, 62, 32, 43, 49, 74, 12, 60, 22, 44, 61, 29],
      dtype=int32)

In [26]:
series1 = pd.Series(score1, index=np.arange(0,1000))
series2 = pd.Series(score2, index=np.arange(0,1000))
series2

0      99
1      22
2      64
3      97
4      59
       ..
995    60
996    22
997    44
998    61
999    29
Length: 1000, dtype: int32

In [27]:
df_exams = df_exams.assign(score1=series1, score2=series2)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,38,83,99
1,female,group C,some college,standard,completed,69,90,88,2,22,22
2,female,group B,master's degree,standard,none,90,95,93,39,92,64
3,male,group A,associate's degree,free/reduced,none,47,57,44,88,25,97
4,male,group C,some college,standard,none,76,78,75,21,19,59
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,15,14,60
996,male,group C,high school,free/reduced,none,62,55,55,90,61,22
997,female,group C,high school,free/reduced,completed,59,71,65,73,63,44
998,female,group D,some college,standard,completed,68,78,77,13,6,61
999,female,group D,some college,free/reduced,none,77,86,86,9,60,29

## insert 
Hangi sırada olacağını belirtebiliyorsun

In [28]:
df_exams.insert(1, "test", series1)
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,83,group B,bachelor's degree,standard,none,72,72,74,38,83,99
1,female,22,group C,some college,standard,completed,69,90,88,2,22,22
2,female,92,group B,master's degree,standard,none,90,95,93,39,92,64
3,male,25,group A,associate's degree,free/reduced,none,47,57,44,88,25,97
4,male,19,group C,some college,standard,none,76,78,75,21,19,59
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,14,group E,master's degree,standard,completed,88,99,95,15,14,60
996,male,61,group C,high school,free/reduced,none,62,55,55,90,61,22
997,female,63,group C,high school,free/reduced,completed,59,71,65,73,63,44
998,female,6,group D,some college,standard,completed,68,78,77,13,6,61
999,female,60,group D,some college,free/reduced,none,77,86,86,9,60,29

In [29]:
df_exams["math score"].sum()

np.int64(66089)

In [30]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,83,group B,bachelor's degree,standard,none,72,72,74,38,83,99
1,female,22,group C,some college,standard,completed,69,90,88,2,22,22
2,female,92,group B,master's degree,standard,none,90,95,93,39,92,64
3,male,25,group A,associate's degree,free/reduced,none,47,57,44,88,25,97
4,male,19,group C,some college,standard,none,76,78,75,21,19,59
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,14,group E,master's degree,standard,completed,88,99,95,15,14,60
996,male,61,group C,high school,free/reduced,none,62,55,55,90,61,22
997,female,63,group C,high school,free/reduced,completed,59,71,65,73,63,44
998,female,6,group D,some college,standard,completed,68,78,77,13,6,61
999,female,60,group D,some college,free/reduced,none,77,86,86,9,60,29

In [31]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,83,group B,bachelor's degree,standard,none,72,72,74,38,83,99
1,female,22,group C,some college,standard,completed,69,90,88,2,22,22
2,female,92,group B,master's degree,standard,none,90,95,93,39,92,64
3,male,25,group A,associate's degree,free/reduced,none,47,57,44,88,25,97
4,male,19,group C,some college,standard,none,76,78,75,21,19,59
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,14,group E,master's degree,standard,completed,88,99,95,15,14,60
996,male,61,group C,high school,free/reduced,none,62,55,55,90,61,22
997,female,63,group C,high school,free/reduced,completed,59,71,65,73,63,44
998,female,6,group D,some college,standard,completed,68,78,77,13,6,61
999,female,60,group D,some college,free/reduced,none,77,86,86,9,60,29

In [32]:
df_exams["average"] = (df_exams["math score"] + df_exams["reading score"] + df_exams["writing score"]) / 3
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average
0,female,83,group B,bachelor's degree,standard,none,72,72,74,38,83,99,72.666667
1,female,22,group C,some college,standard,completed,69,90,88,2,22,22,82.333333
2,female,92,group B,master's degree,standard,none,90,95,93,39,92,64,92.666667
3,male,25,group A,associate's degree,free/reduced,none,47,57,44,88,25,97,49.333333
4,male,19,group C,some college,standard,none,76,78,75,21,19,59,76.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,14,group E,master's degree,standard,completed,88,99,95,15,14,60,94.000000
996,male,61,group C,high school,free/reduced,none,62,55,55,90,61,22,57.333333
997,female,63,group C,high school,free/reduced,completed,59,71,65,73,63,44,65.000000
998,female,6,group D,some college,standard,completed,68,78,77,13,6,61,74.333333
999,female,60,group D,some college,free/reduced,none,77,86,86,9,60,29,83.000000

# değer sayıları

In [33]:
df_exams["gender"].count()

np.int64(1000)

In [34]:
df_exams["gender"].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [35]:
df_exams["gender"].value_counts(normalize=True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [36]:
df_exams['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [37]:
df_exams['parental level of education'].value_counts(normalize=True)

parental level of education
some college          0.226
associate's degree    0.222
high school           0.196
some high school      0.179
bachelor's degree     0.118
master's degree       0.059
Name: proportion, dtype: float64

In [38]:
df_exams['parental level of education'].value_counts(normalize=True).round(2)

parental level of education
some college          0.23
associate's degree    0.22
high school           0.20
some high school      0.18
bachelor's degree     0.12
master's degree       0.06
Name: proportion, dtype: float64

# sıralama

In [40]:
df_exams.sort_values("math score", ascending=False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average
962,female,30,group E,associate's degree,standard,none,100,100,100,46,30,71,100.000000
625,male,61,group D,some college,standard,completed,100,97,99,43,61,67,98.666667
458,female,57,group E,bachelor's degree,standard,none,100,100,100,34,57,88,100.000000
623,male,7,group A,some college,standard,completed,100,96,86,38,7,58,94.000000
451,female,69,group E,some college,standard,none,100,92,97,3,69,72,96.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,44,group C,some college,free/reduced,none,22,39,33,38,44,93,31.333333
787,female,54,group B,some college,standard,none,19,38,32,96,54,48,29.666667
17,female,11,group B,some high school,free/reduced,none,18,32,28,42,11,1,26.000000
980,female,84,group B,high school,free/reduced,none,8,24,23,82,84,89,18.333333
59,female,84,group C,some high school,free/reduced,none,0,17,10,46,84,71,9.000000

In [41]:
df_exams.sort_values(['math score', 'reading score'], ascending=False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average
149,male,38,group E,associate's degree,free/reduced,completed,100,100,93,46,38,83,97.666667
458,female,57,group E,bachelor's degree,standard,none,100,100,100,34,57,88,100.000000
916,male,92,group E,bachelor's degree,standard,completed,100,100,100,29,92,28,100.000000
962,female,30,group E,associate's degree,standard,none,100,100,100,46,30,71,100.000000
625,male,61,group D,some college,standard,completed,100,97,99,43,61,67,98.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,44,group C,some college,free/reduced,none,22,39,33,38,44,93,31.333333
787,female,54,group B,some college,standard,none,19,38,32,96,54,48,29.666667
17,female,11,group B,some high school,free/reduced,none,18,32,28,42,11,1,26.000000
980,female,84,group B,high school,free/reduced,none,8,24,23,82,84,89,18.333333
59,female,84,group C,some high school,free/reduced,none,0,17,10,46,84,71,9.000000

# index değiştirme

new_index = np.arange(0, 1000)
random.shuffle(new_index)
df_exams['new_index'] = new_index
df_exams.set_index('new_index', inplace=True)

SORT INDEX
df_exams.sort_index()

# SÜTUN İSİMLERİ DEĞİŞTİRME

In [45]:
df_exams = df_exams.rename(columns={"gender":"Gender"})
df_exams.head()

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,language score,score1,score2,average
0,female,83,group B,bachelor's degree,standard,none,72,72,74,38,83,99,72.666667
1,female,22,group C,some college,standard,completed,69,90,88,2,22,22,82.333333
2,female,92,group B,master's degree,standard,none,90,95,93,39,92,64,92.666667
3,male,25,group A,associate's degree,free/reduced,none,47,57,44,88,25,97,49.333333
4,male,19,group C,some college,standard,none,76,78,75,21,19,59,76.333333

In [44]:
df_exams.rename(columns={'math score':'MS', 'reading score':'RS', 'writing score':'WS'}, inplace=True)
df_exams.head()

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,language score,score1,score2,average
0,female,83,group B,bachelor's degree,standard,none,72,72,74,38,83,99,72.666667
1,female,22,group C,some college,standard,completed,69,90,88,2,22,22,82.333333
2,female,92,group B,master's degree,standard,none,90,95,93,39,92,64,92.666667
3,male,25,group A,associate's degree,free/reduced,none,47,57,44,88,25,97,49.333333
4,male,19,group C,some college,standard,none,76,78,75,21,19,59,76.333333

# INDEX İSİM DEĞİŞTİRME

In [46]:
df_exams.rename(index={0:"A", 1:"B", 2:"C"}, inplace=True)
df_exams.head(3)

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,language score,score1,score2,average
A,female,83,group B,bachelor's degree,standard,none,72,72,74,38,83,99,72.666667
B,female,22,group C,some college,standard,completed,69,90,88,2,22,22,82.333333
C,female,92,group B,master's degree,standard,none,90,95,93,39,92,64,92.666667